cache: cargo
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
os:
  - linux
  - osx
before_script:
  - curl -o ${TRAVIS_BUILD_DIR}/6br/hgb/test/index_test.bam https://github.com/plotly/react-genome-viewer/raw/master/demo/data/index_test.bam
  - curl -o ${TRAVIS_BUILD_DIR}/6br/hgb/test/index_test.bam.bai https://github.com/plotly/react-genome-viewer/raw/master/demo/data/index_test.bam.bai
  - curl -o ${TRAVIS_BUILD_DIR}/6br/hgb/test/test-in.bam https://github.com/ingolia/SamTools/raw/master/samtools/test/test-in.bam
  - curl -o ${TRAVIS_BUILD_DIR}/6br/hgb/test/test-in.bam.bai https://github.com/ingolia/SamTools/raw/master/samtools/test/test-in.bam.bai