[package]
name = "rust_project"
version = "0.1.0"
authors = ["6br <tfdvrt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_project"
crate-type = ["staticlib", "cdylib"]

[dependencies]
#bam = "*" 
#bam = { git = "https://bitbucket.org/6br/bam" }
bam = { path = "../../../gitlab.com/tprodanov/bam" }
bio = { git = "https://github.com/rust-bio/rust-bio" }
bitpacking = "0.5" # Pfor
byteorder = "*"
env_logger = "*"
flate2 = "1.0" # A streaming compression/decompression library
libflate = "0.1"
log = "*"
numpress = "1.0"
regex = "*" 
serde = "*"
serde_json = "*"
serde_yaml = "*"
vbyte = { git = "https://github.com/6br/vbyte" }
