[package]
name = "rust_project"
version = "0.1.0"
authors = ["6br <tfdvrt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ghi"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "ghi"
path = "src/main.rs"

[dependencies]
#bam = "*" 
#bam = { git = "https://bitbucket.org/6br/bam" }
bam = { path = "../../../gitlab.com/tprodanov/bam" }
bio = { git = "https://github.com/rust-bio/rust-bio" }
csv = "1.1.3"
bitpacking = "0.8.2"
byteorder = "1.3.4"
env_logger = "0.7.1"
flate2 = "1.0.14"
genomic_range = { git = "https://github.com/6br/genomic_range" }
libflate = "1.0.0"
log = "0.4.8"
numpress = "1.1.0"
rayon="*"
regex = "1.3.7"
serde = "1.0.110"
serde_json = "1.0.53"
serde_yaml = "0.8.12"
vbyte = { git = "https://github.com/6br/vbyte" }

[dependencies.clap]
git = "https://github.com/clap-rs/clap"
#version = "3.0.0-beta.1"
default-features = false

# Cherry-pick the features you'd like to use
features = [ "suggestions", "color", "std" ]
