name: daily

on:
  schedule:
    - cron: "0 0 * * *"
  push: 
    branches:
      "master"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly-2022-02-27
          - nightly
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy
    - name: initialize
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install samtools lld -y
        export RUSTFLAGS="-C link-arg=-fuse-ld=lld"
    - name: initialize
      if: matrix.os == 'macos-latest'
      run: |
        brew install samtools
    - name: Build
      run: cargo build --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Run tests
      run:  |
        curl -L https://github.com/plotly/react-genome-viewer/raw/master/demo/data/index_test.bam -o ${GITHUB_WORKSPACE}/test/index_test.bam
        curl -L https://github.com/plotly/react-genome-viewer/raw/master/demo/data/index_test.bam.bai -o ${GITHUB_WORKSPACE}/test/index_test.bam.bai
        curl -L https://github.com/ingolia/SamTools/raw/master/samtools/test/test-in.bam -o ${GITHUB_WORKSPACE}/test/test-in.bam
        curl -L https://github.com/ingolia/SamTools/raw/master/samtools/test/test-in.bam.bai -o ${GITHUB_WORKSPACE}/test/test-in.bam.bai
        ls -lh test/
        echo `pwd`
        cargo test --verbose
    - name: Build
      run: cargo build --no-default-features --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Run tests
      run:  |
        curl -L https://github.com/plotly/react-genome-viewer/raw/master/demo/data/index_test.bam -o ${GITHUB_WORKSPACE}/test/index_test.bam
        curl -L https://github.com/plotly/react-genome-viewer/raw/master/demo/data/index_test.bam.bai -o ${GITHUB_WORKSPACE}/test/index_test.bam.bai
        curl -L https://github.com/ingolia/SamTools/raw/master/samtools/test/test-in.bam -o ${GITHUB_WORKSPACE}/test/test-in.bam
        curl -L https://github.com/ingolia/SamTools/raw/master/samtools/test/test-in.bam.bai -o ${GITHUB_WORKSPACE}/test/test-in.bam.bai
        ls -lh test/
        echo `pwd`
        cargo test --verbose
